# Generated by Django 4.1.7 on 2023-03-21 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bodega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_bodega', models.CharField(max_length=200, verbose_name='Bodega')),
                ('descripcion_bodega', models.CharField(blank=True, max_length=300, null=True)),
                ('usuario_crea', models.CharField(blank=True, max_length=20, null=True)),
                ('fecha_crea', models.DateField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'BODEGA',
            },
        ),
        migrations.CreateModel(
            name='CalidadProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_calidad', models.CharField(max_length=200)),
                ('usuario_crea', models.CharField(max_length=20)),
                ('fecha_crea', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'CALIDAD_PRODUCTO',
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('rut_empresa', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nombre_empresa', models.CharField(max_length=100, verbose_name='Empresa')),
                ('correo_empresa', models.CharField(blank=True, max_length=300, null=True)),
                ('estado_empresa', models.BooleanField(blank=True, null=True)),
                ('fecha_vigencia', models.DateField(blank=True, null=True)),
                ('fecha_crea', models.DateField(auto_now_add=True)),
                ('usuario_crea', models.CharField(blank=True, max_length=20, null=True)),
                ('nombre_fantasia', models.CharField(blank=True, max_length=100, null=True)),
                ('ciudad', models.CharField(blank=True, max_length=100, null=True)),
                ('telefono', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'EMPRESA',
            },
        ),
        migrations.CreateModel(
            name='Linea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_linea', models.CharField(max_length=200, verbose_name='Linea')),
                ('descripcion_linea', models.CharField(blank=True, max_length=300, null=True)),
                ('usuario_crea', models.CharField(blank=True, max_length=20, null=True)),
                ('fecha_crea', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'LINEA',
            },
        ),
        migrations.CreateModel(
            name='PatronCorte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_patron', models.CharField(max_length=300)),
                ('descripcion_patron', models.CharField(blank=True, max_length=500, null=True)),
                ('usuario_crea', models.CharField(blank=True, max_length=30, null=True)),
                ('fecha_crea', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'PATRON_CORTE',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_producto', models.CharField(max_length=300, verbose_name='Producto')),
                ('descripcion_producto', models.CharField(blank=True, max_length=500, null=True)),
                ('espesor_producto', models.FloatField(blank=True, null=True)),
                ('ancho_producto', models.FloatField(blank=True, null=True)),
                ('largo_producto', models.FloatField(blank=True, null=True)),
                ('usuario_crea', models.CharField(max_length=20)),
                ('fecha_crea', models.DateField(auto_now_add=True)),
                ('calidad_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.calidadproducto', verbose_name='Calidad de Producto')),
            ],
            options={
                'db_table': 'PRODUCTO',
            },
        ),
        migrations.CreateModel(
            name='Rollizo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_rollizo', models.CharField(max_length=300)),
                ('descripcion_rollizo', models.CharField(blank=True, max_length=500, null=True)),
                ('diametro', models.IntegerField()),
                ('usuario_crea', models.CharField(blank=True, max_length=20, null=True)),
                ('fecha_crea', models.DateField(auto_now_add=True)),
                ('id_patron', models.IntegerField(blank=True, null=True)),
                ('clase_diametrica', models.IntegerField(blank=True, null=True)),
                ('linea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.linea', verbose_name='Linea')),
            ],
            options={
                'db_table': 'ROLLIZO',
            },
        ),
        migrations.CreateModel(
            name='RollizoLargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_largo', models.CharField(max_length=200)),
                ('descripcion_largo', models.CharField(blank=True, max_length=300, null=True)),
                ('largo', models.FloatField()),
                ('usuario_crea', models.CharField(blank=True, max_length=20, null=True)),
                ('fecha_crea', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'ROLLIZO_LARGO',
            },
        ),
        migrations.CreateModel(
            name='TipoPeriodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_tipo_periodo', models.CharField(max_length=200)),
                ('descripcion_tipo_periodo', models.CharField(blank=True, max_length=500, null=True)),
                ('dias', models.IntegerField(blank=True, null=True)),
                ('usuario_crea', models.CharField(blank=True, max_length=20, null=True)),
                ('fecha_crea', models.DateField(auto_now_add=True)),
                ('empresa', models.OneToOneField(db_column='rut_empresa', on_delete=django.db.models.deletion.CASCADE, to='core.empresa', verbose_name='Empresa')),
            ],
            options={
                'db_table': 'TIPO_PERIODO',
            },
        ),
        migrations.CreateModel(
            name='TiempoCambio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.FloatField()),
                ('usuario_crea', models.CharField(blank=True, max_length=20, null=True)),
                ('fecha_crea', models.DateField(auto_now_add=True)),
                ('linea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.linea', verbose_name='Linea')),
            ],
            options={
                'db_table': 'TIEMPO_CAMBIO',
            },
        ),
        migrations.CreateModel(
            name='StockRollizo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.FloatField()),
                ('usuario_crea', models.CharField(blank=True, max_length=20, null=True)),
                ('fecha_crea', models.DateField(auto_now_add=True)),
                ('bodega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.bodega', verbose_name='Bodega')),
                ('rollizo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.rollizo', verbose_name='Rollizo')),
            ],
            options={
                'db_table': 'STOCK_ROLLIZO',
            },
        ),
        migrations.CreateModel(
            name='StockProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_m3', models.FloatField()),
                ('fecha_crea', models.DateField(auto_now_add=True)),
                ('usuario_crea', models.CharField(blank=True, max_length=20, null=True)),
                ('bodega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.bodega', verbose_name='Bodega')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.producto', verbose_name='Producto')),
            ],
            options={
                'db_table': 'STOCK_PRODUCTO',
            },
        ),
        migrations.AddField(
            model_name='rollizo',
            name='rollizo_largo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.rollizolargo', verbose_name='Largo'),
        ),
        migrations.CreateModel(
            name='ProductosEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.ForeignKey(db_column='rut_empresa', on_delete=django.db.models.deletion.CASCADE, to='core.empresa')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.producto')),
            ],
            options={
                'db_table': 'PRODUCTOS_EMPRESA',
            },
        ),
        migrations.CreateModel(
            name='ProductoCorte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_producto', models.IntegerField(blank=True, null=True)),
                ('descripcion_corte', models.CharField(blank=True, max_length=200, null=True)),
                ('usuario_crea', models.CharField(blank=True, max_length=20, null=True)),
                ('fecha_crea', models.DateField(auto_now_add=True, null=True)),
                ('patron', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.patroncorte', verbose_name='Patrón de Corte')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.producto', verbose_name='Producto')),
                ('rollizo', models.ForeignKey(blank=True, db_column='id_rollizo', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.rollizo')),
            ],
            options={
                'db_table': 'PRODUCTO_CORTE',
            },
        ),
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_periodo', models.CharField(blank=True, max_length=200, null=True)),
                ('descripcion_periodo', models.CharField(blank=True, max_length=300, null=True)),
                ('cantidad_periodos', models.IntegerField(blank=True, null=True)),
                ('usuario_crea', models.CharField(blank=True, max_length=20, null=True)),
                ('fecha_crea', models.DateField(auto_now_add=True)),
                ('tipo_periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tipoperiodo', verbose_name='Tipo de Periodo')),
            ],
            options={
                'db_table': 'PERIODO',
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_pedido', models.CharField(max_length=200, verbose_name='Número de Pedido')),
                ('destino_pedido', models.CharField(max_length=300)),
                ('fecha_recepcion', models.DateField()),
                ('fecha_entrega', models.DateField()),
                ('usuario_crea', models.CharField(blank=True, max_length=20, null=True)),
                ('fecha_crea', models.DateField(auto_now_add=True)),
                ('estado_pedido', models.BooleanField()),
                ('prioridad', models.CharField(choices=[('Alta', 'Alta'), ('Media', 'Media'), ('Baja', 'Baja')], max_length=10)),
                ('empresa', models.ForeignKey(db_column='rut_empresa', on_delete=django.db.models.deletion.CASCADE, to='core.empresa', verbose_name='Empresa')),
            ],
            options={
                'db_table': 'PEDIDO',
            },
        ),
        migrations.CreateModel(
            name='LineaHhDisponible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_bloque', models.IntegerField()),
                ('cantidad_hh', models.IntegerField()),
                ('usuario_crea', models.CharField(blank=True, max_length=20, null=True)),
                ('fecha_crea', models.DateField(auto_now_add=True)),
                ('empresa', models.ForeignKey(db_column='rut_empresa', on_delete=django.db.models.deletion.CASCADE, to='core.empresa', verbose_name='Empresa')),
                ('linea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.linea', verbose_name='Linea')),
            ],
            options={
                'db_table': 'LINEA_HH_DISPONIBLE',
            },
        ),
        migrations.AddField(
            model_name='empresa',
            name='productos',
            field=models.ManyToManyField(through='core.ProductosEmpresa', to='core.producto'),
        ),
        migrations.CreateModel(
            name='DetallePedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detalle_producto', models.CharField(max_length=300)),
                ('volumen_producto', models.CharField(max_length=10)),
                ('fecha_entrega', models.DateField()),
                ('estado_pedido_linea', models.IntegerField(blank=True, null=True)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.pedido', verbose_name='Pedido')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.producto', verbose_name='Producto')),
            ],
            options={
                'db_table': 'DETALLE_PEDIDO',
            },
        ),
        migrations.CreateModel(
            name='CostoSobreTiempo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.FloatField()),
                ('usuario_crea', models.CharField(blank=True, max_length=20, null=True)),
                ('fecha_crea', models.DateField(auto_now_add=True)),
                ('empresa', models.ForeignKey(blank=True, db_column='rut_empresa', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.empresa', verbose_name='Empresa')),
                ('tiempo_cambio', models.OneToOneField(blank=True, db_column='id_tiempo_cambio', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.tiempocambio', verbose_name='Tiempo de Cambio')),
            ],
            options={
                'db_table': 'COSTO_SOBRE_TIEMPO',
            },
        ),
        migrations.CreateModel(
            name='CostoRollizo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_costo', models.CharField(max_length=200)),
                ('valor_m3', models.FloatField()),
                ('fecha_crea', models.DateField(auto_now_add=True)),
                ('usuario_crea', models.CharField(blank=True, max_length=20, null=True)),
                ('empresa', models.ForeignKey(db_column='rut_empresa', on_delete=django.db.models.deletion.CASCADE, to='core.empresa', verbose_name='Empresa')),
                ('linea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.linea', verbose_name='Linea')),
            ],
            options={
                'db_table': 'COSTO_ROLLIZO',
            },
        ),
        migrations.AddField(
            model_name='bodega',
            name='empresa',
            field=models.ForeignKey(db_column='rut_empresa', on_delete=django.db.models.deletion.CASCADE, to='core.empresa', verbose_name='Empresa'),
        ),
        migrations.CreateModel(
            name='AbastecimientoRollizo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_bloque', models.IntegerField(blank=True, null=True)),
                ('cantidad_hh', models.IntegerField(blank=True, null=True)),
                ('usuario_crea', models.CharField(blank=True, max_length=20, null=True)),
                ('fecha_crea', models.DateField(auto_now_add=True)),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.periodo', verbose_name='Periodo')),
                ('rollizo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.rollizo', verbose_name='Rollizo')),
            ],
            options={
                'db_table': 'ABASTECIMIENTO_ROLLIZO',
                'ordering': ['id'],
            },
        ),
    ]
