# Generated by Django 4.1.7 on 2023-03-18 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='calidadproducto',
            table='CALIDAD_PRODUCTO',
        ),
    ]
