# Generated by Django 4.1.6 on 2023-02-06 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_userprofile_nombre_userprofile_password_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='password',
        ),
    ]
