# Generated by Django 4.1.7 on 2023-03-18 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_calidadproducto_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bodega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_bodega', models.CharField(max_length=200, verbose_name='Bodega')),
                ('descripcion_bodega', models.CharField(blank=True, max_length=300, null=True)),
                ('usuario_crea', models.CharField(blank=True, max_length=20, null=True)),
                ('fecha_crea', models.DateField(auto_now_add=True)),
                ('empresa', models.ForeignKey(db_column='rut_empresa', on_delete=django.db.models.deletion.CASCADE, to='core.empresa', verbose_name='Empresa')),
            ],
            options={
                'db_table': 'BODEGA',
            },
        ),
        migrations.CreateModel(
            name='Linea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_linea', models.CharField(max_length=200, verbose_name='Linea')),
                ('descripcion_linea', models.CharField(blank=True, max_length=300, null=True)),
                ('usuario_crea', models.CharField(blank=True, max_length=20, null=True)),
                ('fecha_crea', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'LINEA',
            },
        ),
        migrations.CreateModel(
            name='PatronCorte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_patron', models.CharField(max_length=300)),
                ('descripcion_patron', models.CharField(blank=True, max_length=500, null=True)),
                ('usuario_crea', models.CharField(blank=True, max_length=30, null=True)),
                ('fecha_crea', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'PATRON_CORTE',
            },
        ),
        migrations.CreateModel(
            name='Rollizo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_rollizo', models.CharField(max_length=300)),
                ('descripcion_rollizo', models.CharField(blank=True, max_length=500, null=True)),
                ('diametro', models.IntegerField()),
                ('usuario_crea', models.CharField(blank=True, max_length=20, null=True)),
                ('fecha_crea', models.DateField(auto_now_add=True)),
                ('id_patron', models.IntegerField(blank=True, null=True)),
                ('clase_diametrica', models.IntegerField(blank=True, null=True)),
                ('linea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.linea', verbose_name='Linea')),
            ],
            options={
                'db_table': 'ROLLIZO',
            },
        ),
        migrations.CreateModel(
            name='RollizoLargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_largo', models.CharField(max_length=200)),
                ('descripcion_largo', models.CharField(blank=True, max_length=300, null=True)),
                ('largo', models.FloatField()),
                ('usuario_crea', models.CharField(blank=True, max_length=20, null=True)),
                ('fecha_crea', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'ROLLIZO_LARGO',
            },
        ),
        migrations.RenameField(
            model_name='productosempresa',
            old_name='id_producto',
            new_name='producto',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='rut_empresa',
            new_name='empresa',
        ),
        migrations.CreateModel(
            name='TipoPeriodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_tipo_periodo', models.CharField(max_length=200)),
                ('descripcion_tipo_periodo', models.CharField(blank=True, max_length=500, null=True)),
                ('dias', models.IntegerField(blank=True, null=True)),
                ('usuario_crea', models.CharField(blank=True, max_length=20, null=True)),
                ('fecha_crea', models.DateField(auto_now_add=True)),
                ('rut_empresa', models.OneToOneField(db_column='rut_empresa', on_delete=django.db.models.deletion.CASCADE, to='core.empresa', verbose_name='Empresa')),
            ],
            options={
                'db_table': 'TIPO_PERIODO',
            },
        ),
        migrations.CreateModel(
            name='TiempoCambio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.FloatField()),
                ('usuario_crea', models.CharField(blank=True, max_length=20, null=True)),
                ('fecha_crea', models.DateField(auto_now_add=True)),
                ('linea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.linea', verbose_name='Linea')),
            ],
            options={
                'db_table': 'TIEMPO_CAMBIO',
            },
        ),
        migrations.CreateModel(
            name='StockRollizo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.FloatField()),
                ('usuario_crea', models.CharField(blank=True, max_length=20, null=True)),
                ('fecha_crea', models.DateField(auto_now_add=True)),
                ('bodega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.bodega', verbose_name='Bodega')),
                ('rollizo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.rollizo', verbose_name='Rollizo')),
            ],
            options={
                'db_table': 'STOCK_ROLLIZO',
            },
        ),

        migrations.AddField(
            model_name='rollizo',
            name='rollizo_largo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.rollizolargo', verbose_name='Largo'),
        ),
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_periodo', models.CharField(blank=True, max_length=200, null=True)),
                ('descripcion_periodo', models.CharField(blank=True, max_length=300, null=True)),
                ('cantidad_periodos', models.IntegerField(blank=True, null=True)),
                ('usuario_crea', models.CharField(blank=True, max_length=20, null=True)),
                ('fecha_crea', models.DateField(auto_now_add=True)),
                ('tipo_periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tipoperiodo', verbose_name='Tipo de Periodo')),
            ],
            options={
                'db_table': 'PERIODO',
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_pedido', models.CharField(max_length=200, verbose_name='Número de Pedido')),
                ('destino_pedido', models.CharField(max_length=300)),
                ('fecha_recepcion', models.DateField()),
                ('fecha_entrega', models.DateField()),
                ('usuario_crea', models.CharField(blank=True, max_length=20, null=True)),
                ('fecha_crea', models.DateField(auto_now_add=True)),
                ('estado_pedido', models.BooleanField()),
                ('prioridad', models.CharField(choices=[('Alta', 'Alta'), ('Media', 'Media'), ('Baja', 'Baja')], max_length=10)),
                ('rut_empresa', models.ForeignKey(db_column='rut_empresa', on_delete=django.db.models.deletion.CASCADE, to='core.empresa', verbose_name='Empresa')),
            ],
            options={
                'db_table': 'PEDIDO',
            },
        ),
        migrations.CreateModel(
            name='LineaHhDisponible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_bloque', models.IntegerField()),
                ('cantidad_hh', models.IntegerField()),
                ('usuario_crea', models.CharField(blank=True, max_length=20, null=True)),
                ('fecha_crea', models.DateField(auto_now_add=True)),
                ('linea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.linea', verbose_name='Linea')),
                ('rut_empresa', models.ForeignKey(db_column='rut_empresa', on_delete=django.db.models.deletion.CASCADE, to='core.empresa', verbose_name='Empresa')),
            ],
            options={
                'db_table': 'LINEA_HH_DISPONIBLE',
            },
        ),
        migrations.CreateModel(
            name='DetallePedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detalle_producto', models.CharField(max_length=300)),
                ('volumen_producto', models.CharField(max_length=10)),
                ('fecha_entrega', models.DateField()),
                ('estado_pedido_linea', models.IntegerField(blank=True, null=True)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.pedido', verbose_name='Pedido')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.producto', verbose_name='Producto')),
            ],
            options={
                'db_table': 'DETALLE_PEDIDO',
            },
        ),
        migrations.CreateModel(
            name='CostoRollizo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_costo', models.CharField(max_length=200)),
                ('valor_m3', models.FloatField()),
                ('fecha_crea', models.DateField(auto_now_add=True)),
                ('usuario_crea', models.CharField(blank=True, max_length=20, null=True)),
                ('empresa', models.ForeignKey(db_column='rut_empresa', on_delete=django.db.models.deletion.CASCADE, to='core.empresa', verbose_name='Empresa')),
                ('linea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.linea', verbose_name='Linea')),
            ],
            options={
                'db_table': 'COSTO_ROLLIZO',
            },
        ),
        migrations.CreateModel(
            name='AbastecimientoRollizo',
            fields=[
                ('id_abastecimiento', models.AutoField(primary_key=True, serialize=False)),
                ('numero_bloque', models.IntegerField(blank=True, null=True)),
                ('cantidad_hh', models.IntegerField(blank=True, null=True)),
                ('usuario_crea', models.CharField(blank=True, max_length=20, null=True)),
                ('fecha_crea', models.DateField(auto_now_add=True, null=True)),
                ('id_periodo', models.ForeignKey(blank=True, db_column='id_periodo', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.periodo', verbose_name='Periodo')),
                ('id_rollizo', models.ForeignKey(blank=True, db_column='id_rollizo', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.rollizo', verbose_name='Rollizo')),
            ],
            options={
                'db_table': 'ABASTECIMIENTO_ROLLIZO',
                'ordering': ['id_abastecimiento'],
            },
        ),
                migrations.CreateModel(
            name='StockProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_m3', models.FloatField()),
                ('fecha_crea', models.DateField(auto_now_add=True)),
                ('usuario_crea', models.CharField(blank=True, max_length=20, null=True)),
                ('bodega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.bodega', verbose_name='Bodega')),
                ('detalle', models.ForeignKey('DetallePedido', on_delete=models.CASCADE, verbose_name='DetallePedido'))
            ],
            options={
                'db_table': 'STOCK_PRODUCTO',
            },
        ),
    ]
