# Generated by Django 4.1.7 on 2023-03-18 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_bodega_linea_patroncorte_rollizo_rollizolargo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lineahhdisponible',
            old_name='rut_empresa',
            new_name='empresa',
        ),
        migrations.RenameField(
            model_name='pedido',
            old_name='rut_empresa',
            new_name='empresa',
        ),
        migrations.RenameField(
            model_name='productosempresa',
            old_name='rut_empresa',
            new_name='empresa',
        ),
        migrations.RenameField(
            model_name='tipoperiodo',
            old_name='rut_empresa',
            new_name='empresa',
        ),
    ]
