# Generated by Django 4.1.6 on 2023-02-07 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_userprofile_nombre_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='role',
        ),
    ]
