# Generated by Django 4.1.7 on 2023-03-18 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_rut_empresa_lineahhdisponible_empresa_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductoCorte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_producto', models.IntegerField(blank=True, null=True)),
                ('descripcion_corte', models.CharField(blank=True, max_length=200, null=True)),
                ('usuario_crea', models.CharField(blank=True, max_length=20, null=True)),
                ('fecha_crea', models.DateField(auto_now_add=True, null=True)),
                ('patron', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.patroncorte', verbose_name='Patrón de Corte')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.producto', verbose_name='Producto')),
                ('rollizo', models.ForeignKey(blank=True, db_column='id_rollizo', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.rollizo')),
            ],
            options={
                'db_table': 'PRODUCTO_CORTE',
            },
        ),
    ]
