# Generated by Django 4.1.6 on 2023-02-14 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_userprofile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='rut_empresa',
            field=models.CharField(default=77003720, max_length=20),
            preserve_default=False,
        ),
    ]
