# Generated by Django 4.1.7 on 2023-03-18 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_productocorte'),
    ]

    operations = [
        migrations.CreateModel(
            name='CostoSobreTiempo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.FloatField()),
                ('usuario_crea', models.CharField(blank=True, max_length=20, null=True)),
                ('fecha_crea', models.DateField(auto_now_add=True)),
                ('empresa', models.ForeignKey(blank=True, db_column='rut_empresa', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.empresa', verbose_name='Empresa')),
                ('tiempo_cambio', models.OneToOneField(blank=True, db_column='id_tiempo_cambio', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.tiempocambio', verbose_name='Tiempo de Cambio')),
            ],
            options={
                'db_table': 'COSTO_SOBRE_TIEMPO',
            },
        ),
    ]
