# Generated by Django 4.1.6 on 2023-02-22 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_userprofile_rut'),
    ]

    operations = [
    ]
