# Generated by Django 4.1.7 on 2023-03-18 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_costosobretiempo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='abastecimientorollizo',
            options={'ordering': ['id']},
        ),
        migrations.RemoveField(
            model_name='abastecimientorollizo',
            name='id_abastecimiento',
        ),
        migrations.RemoveField(
            model_name='abastecimientorollizo',
            name='id_periodo',
        ),
        migrations.RemoveField(
            model_name='abastecimientorollizo',
            name='id_rollizo',
        ),
        migrations.AddField(
            model_name='abastecimientorollizo',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='abastecimientorollizo',
            name='periodo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.periodo', verbose_name='Periodo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='abastecimientorollizo',
            name='rollizo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.rollizo', verbose_name='Rollizo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='abastecimientorollizo',
            name='fecha_crea',
            field=models.DateField(auto_now_add=True),
            preserve_default=False,
        ),
    ]
