# Generated by Django 4.1.6 on 2023-02-22 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_empresa_pedido_producto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empresa',
            options={},
        ),
        migrations.AlterModelOptions(
            name='pedido',
            options={},
        ),
        migrations.AlterModelOptions(
            name='producto',
            options={},
        ),
    ]
