# Generated by Django 4.1.7 on 2023-03-19 00:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_userprofile_empresa_alter_userprofile_rut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='empresa',
            field=models.ForeignKey(db_column='rut_empresa', on_delete=django.db.models.deletion.CASCADE, to='core.empresa'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='rut',
            field=models.CharField(max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
