# Generated by Django 4.1.6 on 2023-02-23 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_bodega_detallepedido_alter_producto_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bodega',
            options={},
        ),
        migrations.AlterModelOptions(
            name='detallepedido',
            options={},
        ),
        migrations.AlterModelOptions(
            name='producto',
            options={},
        ),
    ]
