# Generated by Django 4.1.7 on 2023-03-24 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_bodega_fecha_crea_delete_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallepedido',
            name='estado_pedido_linea',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
