# Generated by Django 4.1.6 on 2023-02-23 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_bodega_options_alter_detallepedido_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Linea',
            fields=[
                ('id_linea', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_linea', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=200, null=True)),
                ('descripcion_linea', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=300, null=True)),
                ('usuario_crea', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=20, null=True)),
                ('fecha_crea', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'LINEA',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='bodega',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='detallepedido',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='empresa',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='pedido',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='producto',
            options={'managed': False},
        ),
    ]
