# Generated by Django 4.1.7 on 2023-03-24 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_detallepedido_estado_pedido_linea'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallepedido',
            name='volumen_producto',
            field=models.FloatField(max_length=10),
        ),
    ]
