# Generated by Django 4.1.6 on 2023-02-23 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_userprofile_rut_empresa'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'managed': False},
        ),
    ]
