# Generated by Django 4.1.7 on 2023-03-28 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_pedido_empresa'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClienteEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cliente', to='core.empresa')),
                ('empresa_oferente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oferente', to='core.empresa')),
            ],
            options={
                'db_table': 'CLIENTE_EMPRESA',
            },
        ),
        migrations.AddConstraint(
            model_name='clienteempresa',
            constraint=models.UniqueConstraint(fields=('empresa_oferente', 'empresa_cliente'), name='unique_relacion_empresa'),
        ),
    ]
