# Generated by Django 4.1.7 on 2023-03-28 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_clienteempresa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='cliente_empresa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.clienteempresa'),
            preserve_default=False,
        ),
    ]
