# Generated by Django 4.1.6 on 2023-02-23 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_userprofile_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bodega',
            options={},
        ),
        migrations.AlterModelOptions(
            name='detallepedido',
            options={},
        ),
        migrations.AlterModelOptions(
            name='empresa',
            options={},
        ),
        migrations.AlterModelOptions(
            name='linea',
            options={},
        ),
        migrations.AlterModelOptions(
            name='pedido',
            options={},
        ),
        migrations.AlterModelOptions(
            name='producto',
            options={},
        ),
    ]
