# Generated by Django 4.1.7 on 2023-03-28 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_pedido_cliente_empresa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rollizo',
            name='id_patron',
        ),
    ]
