# Generated by Django 4.1.6 on 2023-02-24 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_bodega_options_alter_empresa_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bodega',
            options={},
        ),
        migrations.AlterModelOptions(
            name='empresa',
            options={},
        ),
        migrations.AlterModelOptions(
            name='pedido',
            options={},
        ),
    ]
