# Generated by Django 4.1.6 on 2023-02-24 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_bodega_options_alter_empresa_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bodega',
            name='rut_empresa',
            field=models.ForeignKey(blank=True, db_column='rut_empresa', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.empresa'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='estado_empresa',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
