# Generated by Django 4.1.7 on 2023-03-28 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_clienteempresa_fecha_crea_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='productos',
            field=models.ManyToManyField(through='core.DetallePedido', to='core.producto'),
        ),
    ]
