# Generated by Django 4.1.6 on 2023-02-24 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_bodega_rut_empresa_alter_empresa_estado_empresa'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={},
        ),
    ]
