# Generated by Django 4.1.6 on 2023-02-24 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_userprofile_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='rut',
            field=models.CharField(max_length=20),
        ),
    ]
