# Generated by Django 4.1.7 on 2023-03-28 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_invinicialrollizo'),
    ]

    operations = [
        migrations.AddField(
            model_name='invinicialrollizo',
            name='cant_m3',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='invinicialrollizo',
            name='diametro',
            field=models.FloatField(),
        ),
    ]
