# Generated by Django 4.1.7 on 2023-03-30 20:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_invinicialrollizo_cant_m3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clienteempresa',
            name='estado_cliente',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='detallepedido',
            name='volumen_producto',
            field=models.FloatField(max_length=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
