# Generated by Django 4.1.6 on 2023-02-24 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_userprofile_rut_alter_userprofile_rut_empresa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='rut_empresa',
            field=models.ForeignKey(blank=True, db_column='rut_empresa', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.empresa'),
        ),
    ]
