# Generated by Django 4.1.7 on 2023-04-21 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_cliente_remove_pedido_cliente_empresa_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='empresa',
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nombre_cliente',
            field=models.CharField(max_length=100, verbose_name='Cliente'),
        ),
        migrations.CreateModel(
            name='ClienteEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cliente')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.empresa')),
            ],
            options={
                'verbose_name_plural': 'Clientes Empresas',
                'db_table': 'cliente_empresa',
            },
        ),
        migrations.AddField(
            model_name='empresa',
            name='cliente',
            field=models.ManyToManyField(through='core.ClienteEmpresa', to='core.cliente'),
        ),
    ]
