# Generated by Django 4.1.6 on 2023-03-03 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_userprofile_rut_empresa'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductosEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_producto', models.ForeignKey(db_column='id_producto', on_delete=django.db.models.deletion.DO_NOTHING, to='core.producto')),
                ('rut_empresa', models.ForeignKey(db_column='rut_empresa', on_delete=django.db.models.deletion.DO_NOTHING, to='core.empresa')),
            ],
            options={
                'db_table': 'PRODUCTOS_EMPRESA',
                'unique_together': {('rut_empresa', 'id_producto')},
            },
        ),
    ]
