# Generated by Django 4.1.6 on 2023-03-03 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_productosempresa'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockProducto',
            fields=[
                ('id_stock', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad_m3', models.FloatField(blank=True, null=True)),
                ('fecha_crea', models.DateField(blank=True, null=True)),
                ('usuario_crea', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=20, null=True)),
                ('id_bodega', models.ForeignKey(blank=True, db_column='id_bodega', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.bodega')),
                ('id_producto', models.ForeignKey(blank=True, db_column='id_producto', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.producto')),
            ],
            options={
                'db_table': 'STOCK_PRODUCTO',
            },
        ),
    ]
