# Generated by Django 4.1.7 on 2023-04-21 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_remove_empresa_cliente_delete_clienteempresa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='rut_cliente',
        ),
        migrations.AddField(
            model_name='cliente',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
