# Generated by Django 4.1.6 on 2023-03-03 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_stockproducto'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalidadProducto',
            fields=[
                ('id_tipo_calidad', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_calidad', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=200, null=True)),
                ('usuario_crea', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=20, null=True)),
                ('fecha_crea', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'CALIDAD_PRODUCTO',
            },
        ),
    ]
