# Generated by Django 4.1.7 on 2023-04-21 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_clienteempresa_empresa_cliente'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='clienteempresa',
            table='CLIENTE_EMPRESA',
        ),
    ]
