# Generated by Django 4.1.6 on 2023-03-03 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_remove_producto_rut_empresa_producto_id_tipo_calidad'),
    ]

    operations = [
        migrations.CreateModel(
            name='RollizoLargo',
            fields=[
                ('id_largo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_largo', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=200, null=True)),
                ('descripcion_largo', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=300, null=True)),
                ('largo', models.FloatField(blank=True, null=True)),
                ('usuario_crea', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=20, null=True)),
                ('fecha_crea', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ROLLIZO_LARGO',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PatronCorte',
            fields=[
                ('id_patron', models.AutoField(primary_key=True, serialize=False)),
                ('rut_empresa', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=20, null=True)),
                ('nombre_patron', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=300, null=True)),
                ('descripcion_patron', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=500, null=True)),
                ('usuario_crea', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=30, null=True)),
                ('fecha_crea', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'PATRON_CORTE',
            },
        ),
    ]
