# Generated by Django 4.1.6 on 2023-03-03 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_alter_rollizolargo_options_rollizo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patroncorte',
            name='rut_empresa',
        ),
    ]
