# Generated by Django 4.1.7 on 2023-04-21 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_cliente_rut_cliente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clienteempresa',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='clienteempresa',
            name='empresa',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='cliente',
        ),
        migrations.DeleteModel(
            name='Cliente',
        ),
        migrations.DeleteModel(
            name='ClienteEmpresa',
        ),
    ]
