# Generated by Django 4.1.6 on 2023-03-03 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_remove_patroncorte_rut_empresa'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductoCorte',
            fields=[
                ('id_corte', models.AutoField(primary_key=True, serialize=False)),
                ('id_tipo_calidad', models.IntegerField(blank=True, null=True)),
                ('cantidad_producto', models.IntegerField(blank=True, null=True)),
                ('descripcion_corte', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=200, null=True)),
                ('usuario_crea', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=20, null=True)),
                ('fecha_crea', models.DateField(blank=True, null=True)),
                ('id_patron', models.ForeignKey(blank=True, db_column='id_patron', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.patroncorte')),
                ('id_producto', models.ForeignKey(blank=True, db_column='id_producto', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.producto')),
                ('id_rollizo', models.ForeignKey(blank=True, db_column='id_rollizo', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.rollizo')),
            ],
            options={
                'db_table': 'PRODUCTO_CORTE',
            },
        ),
    ]
