# Generated by Django 4.1.7 on 2023-04-21 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='testing',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
