# Generated by Django 4.1.7 on 2023-04-21 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_cliente_testing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='testing',
        ),
    ]
