# Generated by Django 4.1.7 on 2023-04-21 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_remove_cliente_testing'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cliente',
            table='CLIENTEE',
        ),
    ]
