# Generated by Django 4.1.6 on 2023-03-03 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_costosobretiempo'),
    ]

    operations = [
        migrations.CreateModel(
            name='CostoRollizo',
            fields=[
                ('id_costo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_costo', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=200, null=True)),
                ('valor_m3', models.FloatField(blank=True, null=True)),
                ('id_linea', models.IntegerField(blank=True, null=True)),
                ('id_rollizo', models.IntegerField(blank=True, null=True)),
                ('fecha_crea', models.DateField(blank=True, null=True)),
                ('usuario_crea', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=20, null=True)),
            ],
            options={
                'db_table': 'COSTO_ROLLIZO',
            },
        ),
        migrations.CreateModel(
            name='StockRollizo',
            fields=[
                ('id_stock_rollizo', models.AutoField(primary_key=True, serialize=False)),
                ('id_rollizo', models.IntegerField(blank=True, null=True)),
                ('cantidad', models.FloatField(blank=True, null=True)),
                ('usuario_crea', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=20, null=True)),
                ('fecha_crea', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'STOCK_ROLLIZO',
            },
        ),
    ]
