# Generated by Django 4.1.6 on 2023-03-03 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_costorollizo_stockrollizo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='costorollizo',
            name='id_rollizo',
        ),
        migrations.AlterField(
            model_name='costorollizo',
            name='id_linea',
            field=models.ForeignKey(blank=True, db_column='id_linea', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.linea'),
        ),
    ]
