# Generated by Django 4.1.7 on 2023-04-21 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_alter_cliente_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cliente',
        ),
    ]
