# Generated by Django 4.1.6 on 2023-03-03 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_remove_costorollizo_id_rollizo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockrollizo',
            name='id_rollizo',
            field=models.ForeignKey(blank=True, db_column='id_rollizo', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.rollizo'),
        ),
    ]
