# Generated by Django 4.1.7 on 2023-03-06 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_alter_stockrollizo_id_rollizo'),
    ]

    operations = [
        migrations.AddField(
            model_name='costosobretiempo',
            name='id_tiempo_cambio',
            field=models.OneToOneField(blank=True, db_column='id_tiempo_cambio', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.tiempocambio'),
        ),
        migrations.AlterField(
            model_name='costosobretiempo',
            name='rut_empresa',
            field=models.ForeignKey(blank=True, db_column='rut_empresa', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.empresa'),
        ),
        migrations.CreateModel(
            name='TipoPeriodo',
            fields=[
                ('id_tipo_periodo', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_tipo_periodo', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=200, null=True)),
                ('descripcion_tipo_periodo', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=500, null=True)),
                ('dias', models.IntegerField(blank=True, null=True)),
                ('usuario_crea', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=20, null=True)),
                ('fecha_crea', models.DateField(blank=True, null=True)),
                ('rut_empresa', models.OneToOneField(blank=True, db_column='rut_empresa', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.empresa')),
            ],
            options={
                'db_table': 'TIPO_PERIODO',
            },
        ),
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('id_periodo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_periodo', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=200, null=True)),
                ('rut_empresa', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=20, null=True)),
                ('descripcion_periodo', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=300, null=True)),
                ('cantidad_periodos', models.IntegerField(blank=True, null=True)),
                ('usuario_crea', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=20, null=True)),
                ('fecha_crea', models.DateField(blank=True, null=True)),
                ('id_tipo_periodo', models.ForeignKey(blank=True, db_column='id_tipo_periodo', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.tipoperiodo')),
            ],
            options={
                'db_table': 'PERIODO',
            },
        ),
        migrations.CreateModel(
            name='LineaHhDisponible',
            fields=[
                ('id_hh_linea', models.AutoField(primary_key=True, serialize=False)),
                ('id_periodo', models.IntegerField(blank=True, null=True)),
                ('numero_bloque', models.IntegerField(blank=True, null=True)),
                ('cantidad_hh', models.IntegerField(blank=True, null=True)),
                ('usuario_crea', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=20, null=True)),
                ('fecha_crea', models.DateField(blank=True, null=True)),
                ('id_linea', models.ForeignKey(blank=True, db_column='id_linea', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.linea')),
                ('rut_empresa', models.ForeignKey(blank=True, db_column='rut_empresa', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.empresa')),
            ],
            options={
                'db_table': 'LINEA_HH_DISPONIBLE',
            },
        ),
        migrations.CreateModel(
            name='AbastecimientoRollizo',
            fields=[
                ('id_abastecimiento', models.AutoField(primary_key=True, serialize=False)),
                ('numero_bloque', models.IntegerField(blank=True, null=True)),
                ('cantidad_hh', models.IntegerField(blank=True, null=True)),
                ('usuario_crea', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=20, null=True)),
                ('fecha_crea', models.DateField(blank=True, null=True)),
                ('id_periodo', models.ForeignKey(blank=True, db_column='id_periodo', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.periodo')),
                ('id_rollizo', models.ForeignKey(blank=True, db_column='id_rollizo', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.rollizo')),
            ],
            options={
                'db_table': 'ABASTECIMIENTO_ROLLIZO',
            },
        ),
    ]
