# Generated by Django 4.1.7 on 2023-03-06 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_costosobretiempo_id_tiempo_cambio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='costorollizo',
            name='rut_empresa',
            field=models.ForeignKey(blank=True, db_column='rut_empresa', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.empresa'),
        ),
        migrations.AddField(
            model_name='stockrollizo',
            name='id_bodega',
            field=models.ForeignKey(blank=True, db_column='id_bodega', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.bodega'),
        ),
    ]
