# Generated by Django 4.1.7 on 2023-03-06 21:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_costorollizo_rut_empresa_stockrollizo_id_bodega'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='periodo',
            name='rut_empresa',
        ),
        migrations.AlterField(
            model_name='bodega',
            name='rut_empresa',
            field=models.ForeignKey(blank=True, db_column='rut_empresa', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.empresa', verbose_name='Empresa'),
        ),
        migrations.AlterField(
            model_name='costorollizo',
            name='rut_empresa',
            field=models.ForeignKey(blank=True, db_column='rut_empresa', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.empresa', verbose_name='Empresa'),
        ),
        migrations.AlterField(
            model_name='costosobretiempo',
            name='rut_empresa',
            field=models.ForeignKey(blank=True, db_column='rut_empresa', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.empresa', verbose_name='Empresa'),
        ),
        migrations.AlterField(
            model_name='lineahhdisponible',
            name='rut_empresa',
            field=models.ForeignKey(blank=True, db_column='rut_empresa', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.empresa', verbose_name='Empresa'),
        ),
        migrations.AlterField(
            model_name='productosempresa',
            name='id_producto',
            field=models.ForeignKey(db_column='id_producto', on_delete=django.db.models.deletion.DO_NOTHING, to='core.producto', verbose_name='Producto'),
        ),
        migrations.AlterField(
            model_name='productosempresa',
            name='rut_empresa',
            field=models.ForeignKey(db_column='rut_empresa', on_delete=django.db.models.deletion.DO_NOTHING, to='core.empresa', verbose_name='Empresa'),
        ),
        migrations.AlterField(
            model_name='tipoperiodo',
            name='rut_empresa',
            field=models.OneToOneField(blank=True, db_column='rut_empresa', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.empresa', verbose_name='Empresa'),
        ),
    ]
