# Generated by Django 4.1.7 on 2023-03-06 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_remove_periodo_rut_empresa_alter_bodega_rut_empresa_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='abastecimientorollizo',
            options={'ordering': ['id_abastecimiento']},
        ),
        migrations.AlterField(
            model_name='abastecimientorollizo',
            name='fecha_crea',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='bodega',
            name='fecha_crea',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='calidadproducto',
            name='fecha_crea',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='costorollizo',
            name='fecha_crea',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='costosobretiempo',
            name='fecha_crea',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='fecha_crea',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='linea',
            name='fecha_crea',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='lineahhdisponible',
            name='fecha_crea',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='patroncorte',
            name='fecha_crea',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='fecha_crea',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='periodo',
            name='fecha_crea',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='fecha_crea',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='productocorte',
            name='fecha_crea',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='rollizo',
            name='fecha_crea',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='rollizolargo',
            name='fecha_crea',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='stockproducto',
            name='fecha_crea',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='stockrollizo',
            name='fecha_crea',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='tiempocambio',
            name='fecha_crea',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='tipoperiodo',
            name='fecha_crea',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
