# Generated by Django 4.1.7 on 2023-03-06 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_alter_abastecimientorollizo_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='linea',
            name='rut_empresa',
        ),
    ]
