# Generated by Django 4.1.6 on 2023-03-07 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_remove_linea_rut_empresa'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productosempresa',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='productosempresa',
            name='id_pempresa',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productosempresa',
            name='id_producto',
            field=models.ForeignKey(db_column='id_producto', on_delete=django.db.models.deletion.DO_NOTHING, to='core.producto'),
        ),
        migrations.AlterField(
            model_name='productosempresa',
            name='rut_empresa',
            field=models.ForeignKey(db_column='rut_empresa', on_delete=django.db.models.deletion.DO_NOTHING, to='core.empresa'),
        ),
        migrations.AlterUniqueTogether(
            name='productosempresa',
            unique_together={('id_producto', 'rut_empresa')},
        ),
        migrations.RemoveField(
            model_name='productosempresa',
            name='id',
        ),
    ]
