# Generated by Django 4.1.6 on 2023-03-07 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_alter_productosempresa_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productocorte',
            name='id_tipo_calidad',
        ),
    ]
