# Generated by Django 4.1.7 on 2023-05-16 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_remove_costosobretiempo_tiempo_cambio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='ancho_producto',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='espesor_producto',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='largo_producto',
        ),
        migrations.AddField(
            model_name='detallepedido',
            name='ancho_producto',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='detallepedido',
            name='espesor_producto',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='detallepedido',
            name='largo_producto',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
