# Generated by Django 4.1.6 on 2023-03-07 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_alter_abastecimientorollizo_id_periodo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='prioridad',
            field=models.CharField(blank=True, choices=[('Alta', 'Alta'), ('Media', 'Media'), ('Baja', 'Baja')], db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=10, null=True),
        ),
    ]
