# Generated by Django 4.1.6 on 2023-03-09 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_remove_lineahhdisponible_id_periodo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresa',
            name='id_periodo',
        ),
        migrations.AlterField(
            model_name='abastecimientorollizo',
            name='id_periodo',
            field=models.ForeignKey(blank=True, db_column='id_periodo', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.periodo', verbose_name='Periodo'),
        ),
        migrations.AlterField(
            model_name='abastecimientorollizo',
            name='id_rollizo',
            field=models.ForeignKey(blank=True, db_column='id_rollizo', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.rollizo', verbose_name='Rollizo'),
        ),
        migrations.AlterField(
            model_name='bodega',
            name='rut_empresa',
            field=models.ForeignKey(blank=True, db_column='rut_empresa', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.empresa', verbose_name='Empresa'),
        ),
        migrations.AlterField(
            model_name='costorollizo',
            name='id_linea',
            field=models.ForeignKey(blank=True, db_column='id_linea', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.linea', verbose_name='Linea'),
        ),
        migrations.AlterField(
            model_name='costorollizo',
            name='rut_empresa',
            field=models.ForeignKey(blank=True, db_column='rut_empresa', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.empresa', verbose_name='Empresa'),
        ),
        migrations.AlterField(
            model_name='costosobretiempo',
            name='id_tiempo_cambio',
            field=models.OneToOneField(blank=True, db_column='id_tiempo_cambio', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.tiempocambio', verbose_name='Tiempo de Cambio'),
        ),
        migrations.AlterField(
            model_name='costosobretiempo',
            name='rut_empresa',
            field=models.ForeignKey(blank=True, db_column='rut_empresa', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.empresa', verbose_name='Empresa'),
        ),
        migrations.AlterField(
            model_name='detallepedido',
            name='id_pedido',
            field=models.ForeignKey(blank=True, db_column='id_pedido', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.pedido', verbose_name='Pedido'),
        ),
        migrations.AlterField(
            model_name='detallepedido',
            name='id_producto',
            field=models.ForeignKey(blank=True, db_column='id_producto', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.producto', verbose_name='Producto'),
        ),
        migrations.AlterField(
            model_name='lineahhdisponible',
            name='id_linea',
            field=models.ForeignKey(blank=True, db_column='id_linea', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.linea', verbose_name='Linea'),
        ),
        migrations.AlterField(
            model_name='lineahhdisponible',
            name='rut_empresa',
            field=models.ForeignKey(blank=True, db_column='rut_empresa', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.empresa', verbose_name='Empresa'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='rut_empresa',
            field=models.ForeignKey(blank=True, db_column='rut_empresa', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.empresa', verbose_name='Empresa'),
        ),
        migrations.AlterField(
            model_name='periodo',
            name='id_tipo_periodo',
            field=models.ForeignKey(blank=True, db_column='id_tipo_periodo', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.tipoperiodo', verbose_name='Tipo de Periodo'),
        ),
        migrations.AlterField(
            model_name='productocorte',
            name='id_patron',
            field=models.ForeignKey(blank=True, db_column='id_patron', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.patroncorte', verbose_name='Patrón de Corte'),
        ),
        migrations.AlterField(
            model_name='productocorte',
            name='id_producto',
            field=models.ForeignKey(blank=True, db_column='id_producto', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.producto', verbose_name='Producto'),
        ),
        migrations.AlterField(
            model_name='productocorte',
            name='id_rollizo',
            field=models.ForeignKey(blank=True, db_column='id_rollizo', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.rollizo'),
        ),
        migrations.AlterField(
            model_name='productosempresa',
            name='id_producto',
            field=models.ForeignKey(db_column='id_producto', on_delete=django.db.models.deletion.CASCADE, to='core.producto'),
        ),
        migrations.AlterField(
            model_name='productosempresa',
            name='rut_empresa',
            field=models.ForeignKey(db_column='rut_empresa', on_delete=django.db.models.deletion.CASCADE, to='core.empresa'),
        ),
        migrations.AlterField(
            model_name='rollizo',
            name='id_largo',
            field=models.ForeignKey(blank=True, db_column='id_largo', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.rollizolargo', verbose_name='Largo'),
        ),
        migrations.AlterField(
            model_name='rollizo',
            name='id_linea',
            field=models.ForeignKey(blank=True, db_column='id_linea', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.linea', verbose_name='Linea'),
        ),
        migrations.AlterField(
            model_name='stockproducto',
            name='id_bodega',
            field=models.ForeignKey(blank=True, db_column='id_bodega', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.bodega', verbose_name='Bodega'),
        ),
        migrations.AlterField(
            model_name='stockproducto',
            name='id_producto',
            field=models.ForeignKey(blank=True, db_column='id_producto', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.producto', verbose_name='Producto'),
        ),
        migrations.AlterField(
            model_name='stockrollizo',
            name='id_bodega',
            field=models.ForeignKey(blank=True, db_column='id_bodega', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.bodega', verbose_name='Bodega'),
        ),
        migrations.AlterField(
            model_name='stockrollizo',
            name='id_rollizo',
            field=models.ForeignKey(blank=True, db_column='id_rollizo', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.rollizo', verbose_name='Rollizo'),
        ),
        migrations.AlterField(
            model_name='tiempocambio',
            name='id_linea',
            field=models.ForeignKey(blank=True, db_column='id_linea', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.linea', verbose_name='Linea'),
        ),
        migrations.AlterField(
            model_name='tipoperiodo',
            name='rut_empresa',
            field=models.OneToOneField(blank=True, db_column='rut_empresa', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.empresa', verbose_name='Empresa'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='rut_empresa',
            field=models.ForeignKey(blank=True, db_column='rut_empresa', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.empresa'),
        ),
    ]
