# Generated by Django 4.1.8 on 2023-06-15 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_alter_bodega_ubicacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='calidad_producto',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='descripcion_producto',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='fecha_crea',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='nombre_producto',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='usuario_crea',
        ),
        migrations.AddField(
            model_name='producto',
            name='ancho',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='producto',
            name='codigo',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='producto',
            name='grosor',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='producto',
            name='largo',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='producto',
            name='nombre',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterModelTable(
            name='producto',
            table=None,
        ),
    ]
