# Generated by Django 4.1.7 on 2023-03-14 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_remove_empresa_id_periodo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bodega',
            name='nombre_bodega',
            field=models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=200, null=True, verbose_name='Bodega'),
        ),
        migrations.AlterField(
            model_name='linea',
            name='nombre_linea',
            field=models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=200, null=True, verbose_name='Linea'),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
