# Generated by Django 4.1.8 on 2023-06-15 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_remove_producto_calidad_producto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='ancho',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='producto',
            name='codigo',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='producto',
            name='grosor',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='producto',
            name='largo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.CharField(default='', max_length=20),
        ),
    ]
