# Generated by Django 4.1.7 on 2023-03-14 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_alter_bodega_nombre_bodega_alter_linea_nombre_linea_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productosempresa',
            name='id_pempresa',
        ),
        migrations.AddField(
            model_name='productosempresa',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
