# Generated by Django 4.1.7 on 2023-03-14 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_remove_productosempresa_id_pempresa_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productosempresa',
            unique_together=set(),
        ),
    ]
