# Generated by Django 4.1.8 on 2023-06-15 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_alter_producto_ancho_alter_producto_codigo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MateriaPrima',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_buzon', models.IntegerField()),
                ('tipo_madera', models.CharField(max_length=100)),
                ('clase_diametrica', models.CharField(max_length=100)),
                ('longitud', models.FloatField()),
                ('cantidad', models.FloatField()),
            ],
        ),
        migrations.AlterField(
            model_name='producto',
            name='ancho',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='producto',
            name='grosor',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='producto',
            name='largo',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
    ]
