# Generated by Django 4.1.7 on 2023-03-14 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_alter_productosempresa_unique_together'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductosEmpresa',
        ),
    ]
