# Generated by Django 4.1.7 on 2023-03-14 23:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_delete_productosempresa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='rut_empresa',
            field=models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='rut_empresa', max_length=20, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='ProductosEmpresa',
            fields=[
                ('id_pempresa', models.AutoField(primary_key=True, serialize=False)),
                ('id_producto', models.ForeignKey(db_column='id_producto', on_delete=django.db.models.deletion.CASCADE, to='core.producto')),
                ('rut_empresa', models.ForeignKey(db_column='rut_empresa', on_delete=django.db.models.deletion.CASCADE, to='core.empresa')),
            ],
            options={
                'db_table': 'PRODUCTOS_EMPRESA',
            },
        ),
    ]
