# Generated by Django 4.1.7 on 2023-03-14 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0051_alter_empresa_rut_empresa_productosempresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='productos',
            field=models.ManyToManyField(through='core.ProductosEmpresa', to='core.producto'),
        ),
    ]
