# Generated by Django 4.1.8 on 2023-06-16 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0051_alter_producto_ancho_alter_producto_grosor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductoTerminado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=20)),
                ('grosor', models.DecimalField(decimal_places=2, max_digits=5)),
                ('ancho', models.DecimalField(decimal_places=2, max_digits=5)),
                ('largo', models.DecimalField(decimal_places=2, max_digits=5)),
                ('clase_diametrica', models.CharField(max_length=20)),
                ('patron_corte', models.CharField(max_length=50)),
                ('cantidad_producida', models.PositiveIntegerField()),
                ('fecha_produccion', models.DateField()),
            ],
        ),
    ]
