# Generated by Django 4.1.7 on 2023-03-15 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
