# Generated by Django 4.1.8 on 2023-07-03 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_remove_pedido_fecha_crea_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patroncorte',
            name='clase_diametrica_rollizo',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='patroncorte',
            name='codigo_patron',
            field=models.CharField(default='', max_length=20, unique=True),
        ),

    ]
