# Generated by Django 4.1.7 on 2023-03-15 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0054_delete_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('rut', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=20, primary_key=True, serialize=False)),
                ('rut_empresa', models.ForeignKey(db_column='rut_empresa', on_delete=django.db.models.deletion.CASCADE, to='core.empresa')),
            ],
            options={
                'db_table': 'USER_PROFILE',
            },
        ),
    ]
