# Generated by Django 4.1.8 on 2023-07-04 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0054_alter_patroncorte_clase_diametrica_rollizo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='productos_a_producir',
            field=models.CharField(max_length=20),
        ),
    ]
