# Generated by Django 4.1.8 on 2023-07-17 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0055_alter_pedido_productos_a_producir'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materiaprima',
            name='longitud',
        ),
        migrations.AddField(
            model_name='materiaprima',
            name='conicidad',
            field=models.FloatField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='materiaprima',
            name='costo_almacenamiento',
            field=models.FloatField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='materiaprima',
            name='inventario_final',
            field=models.FloatField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='materiaprima',
            name='inventario_inicial',
            field=models.FloatField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='materiaprima',
            name='largo',
            field=models.FloatField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='materiaprima',
            name='linea_produccion',
            field=models.CharField(default='indefinida', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='materiaprima',
            name='volumen_procesado',
            field=models.FloatField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='materiaprima',
            name='cantidad',
            field=models.FloatField(max_length=10),
        ),
        migrations.AlterField(
            model_name='materiaprima',
            name='clase_diametrica',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='materiaprima',
            name='tipo_madera',
            field=models.CharField(max_length=10),
        ),
    ]
