# Generated by Django 4.1.8 on 2023-07-18 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0056_remove_materiaprima_longitud_materiaprima_conicidad_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patroncorte',
            old_name='codigo_patron',
            new_name='codigo',
        ),
        migrations.RenameField(
            model_name='patroncorte',
            old_name='nombre_patron',
            new_name='descripcion',
        ),
        migrations.RemoveField(
            model_name='patroncorte',
            name='clase_diametrica_rollizo',
        ),
        migrations.AddField(
            model_name='patroncorte',
            name='lead_time',
            field=models.FloatField(default=0, max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patroncorte',
            name='nombre',
            field=models.CharField(default='patron', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patroncorte',
            name='rendimiento',
            field=models.FloatField(default=0, max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patroncorte',
            name='rollizo',
            field=models.CharField(default='clase_diametrica', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patroncorte',
            name='setup_time',
            field=models.FloatField(default=0, max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patroncorte',
            name='utilizado',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patroncorte',
            name='velocidad_linea',
            field=models.FloatField(default=0, max_length=5),
            preserve_default=False,
        ),
    ]
