# Generated by Django 4.1.6 on 2023-03-16 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0057_userprofile_id_alter_userprofile_rut'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='id',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='rut',
            field=models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=20, primary_key=True, serialize=False),
        ),
    ]
