# Generated by Django 4.1.8 on 2023-07-19 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0059_rename_estado_pedido_pedido_estado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='linea_produccion',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
