# Generated by Django 4.1.8 on 2023-07-20 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0061_remove_pedido_producto_pedido_productos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='productos',
        ),
        migrations.AddField(
            model_name='pedido',
            name='producto',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
