# Generated by Django 4.1.8 on 2023-07-21 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0062_remove_pedido_productos_pedido_producto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='comentario',
            field=models.CharField(default='Sin comentario', max_length=200, unique=True),
        ),
    ]
