# Generated by Django 4.2.4 on 2023-08-25 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0063_alter_pedido_comentario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Planificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_actual', models.CharField(max_length=50)),
                ('hora_actual', models.CharField(max_length=20, unique=True)),
                ('usuario', models.CharField(default='Sin comentario', max_length=200, unique=True)),
                ('turno', models.CharField(max_length=20)),
                ('clase_diametrica', models.CharField(max_length=20)),
                ('cantidad', models.PositiveIntegerField()),
                ('patron_corte', models.IntegerField()),
                ('productos', models.CharField(max_length=20)),
                ('cantidades', models.CharField(max_length=20)),
                ('rendimiento', models.CharField(max_length=20)),
            ],
        ),
    ]
