# Generated by Django 4.2.4 on 2023-08-25 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0063_alter_pedido_comentario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('Rut', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('telefono', models.CharField(max_length=20)),
                ('empresa', models.CharField(max_length=20)),
                ('rol', models.CharField(max_length=20)),
                ('turno', models.CharField(max_length=20)),
                ('hora_ingreso', models.TimeField()),
                ('hora_salida', models.TimeField()),
                ('contraseña', models.CharField(max_length=50)),
            ],
        ),
    ]
