# Generated by Django 4.2.4 on 2023-08-24 16:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0064_alter_patroncorte_lead_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patroncorte',
            name='rendimiento',
            field=models.FloatField(max_length=5, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
