# Generated by Django 4.2.4 on 2023-08-24 17:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0065_alter_patroncorte_rendimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patroncorte',
            name='rendimiento',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
