# Generated by Django 4.2.4 on 2023-08-24 19:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0066_alter_patroncorte_rendimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patroncorte',
            name='rendimiento',
            field=models.FloatField(max_length=5, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
