# Generated by Django 4.2.4 on 2023-08-24 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0067_alter_patroncorte_rendimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patroncorte',
            name='rendimiento',
            field=models.FloatField(max_length=5),
        ),
    ]
