# Generated by Django 4.2.4 on 2023-08-25 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0069_alter_pedido_prioridad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='prioridad',
            field=models.CharField(choices=[('bajo', 'Bajo'), ('mediano', 'Mediano'), ('alto', 'Alto')], max_length=20),
        ),
    ]
