# Generated by Django 4.2.4 on 2023-08-28 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0070_alter_pedido_prioridad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='codigo',
            field=models.CharField(error_messages={'unique': 'Este código ya existe.'}, max_length=20, unique=True),
        ),
    ]
