# Generated by Django 4.2.4 on 2023-08-29 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0071_alter_pedido_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='codigo',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='prioridad',
            field=models.CharField(max_length=20),
        ),
    ]
