# Generated by Django 4.2.4 on 2023-09-01 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0064_planificacion'),
        ('core', '0064_usuario'),
        ('core', '0072_alter_pedido_codigo_alter_pedido_prioridad'),
    ]

    operations = [
    ]
