# Generated by Django 4.2.4 on 2023-09-01 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0073_merge_20230901_1313'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Planificacion',
        ),
        migrations.AlterField(
            model_name='pedido',
            name='comentario',
            field=models.CharField(default='Sin comentario', max_length=200),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('', 'Seleccione una opción'), ('pendiente', 'Pendiente'), ('en proceso', 'En Proceso'), ('completado', 'Completado')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='linea_produccion',
            field=models.CharField(choices=[('', 'Seleccione una opción'), ('grueso', 'Grueso'), ('delgado', 'Delgado')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='prioridad',
            field=models.CharField(choices=[('', 'Seleccione una opción'), ('bajo', 'Bajo'), ('mediano', 'Mediano'), ('alto', 'Alto')], default='', max_length=20),
        ),
    ]
