# Generated by Django 4.2.4 on 2023-09-07 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0073_merge_20230901_1316'),
        ('core', '0074_delete_planificacion_alter_pedido_comentario_and_more'),
    ]

    operations = [
    ]
