# Generated by Django 4.2.4 on 2023-09-07 18:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0075_merge_20230907_1438'),
    ]

    operations = [
        migrations.CreateModel(
            name='Boletatest',
            fields=[
                ('op', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('mercado', models.CharField(max_length=20)),
                ('fecha_emision', models.CharField(max_length=20)),
                ('eta', models.CharField(max_length=20)),
                ('version', models.CharField(max_length=20)),
                ('comentario', models.CharField(max_length=20)),
                ('destino', models.CharField(max_length=20)),
                ('tipo_empaque', models.CharField(max_length=20)),
                ('alto', models.CharField(max_length=20)),
                ('cant_piezas', models.CharField(max_length=20)),
                ('m3', models.CharField(max_length=20)),
                ('pqte', models.CharField(max_length=20)),
                ('nombreproducto', models.CharField(max_length=20)),
                ('est', models.CharField(max_length=20)),
                ('term', models.CharField(max_length=20)),
                ('calidad', models.CharField(max_length=20)),
                ('fsc', models.CharField(max_length=20)),
                ('espesor', models.CharField(max_length=20)),
                ('ancho', models.CharField(max_length=20)),
                ('largo', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='pedido',
            name='fecha_emision',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='producto',
            field=models.CharField(default='Sin comentario', max_length=20),
        ),
    ]
