# Generated by Django 4.2.4 on 2023-09-07 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0076_boletatest_pedido_fecha_emision_and_more'),
    ]


