# Generated by Django 4.2.4 on 2023-09-21 17:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0078_rename_espesor_producto_detallepedido_alto_producto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallepedido',
            name='grado_urgencia',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='detallepedido',
            name='cantidad_piezas',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='detallepedido',
            name='cantidad_trozos',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='detallepedido',
            name='detalle_producto',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='detallepedido',
            name='fecha_entrega',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='detallepedido',
            name='paquetes_solicitados',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='detallepedido',
            name='piezas_xpaquete',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='detallepedido',
            name='piezas_xtrozo',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='detallepedido',
            name='volumen_producto',
            field=models.FloatField(max_length=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
