# Generated by Django 4.2.4 on 2023-09-13 00:05

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0078_alter_pedido_fecha_emision'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='inventario_inicial',
            new_name='inventario_bodega_inicial',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='inventario_final',
            new_name='inventario_producto_final',
        ),
        migrations.RemoveField(
            model_name='materiaprima',
            name='costo_almacenamiento',
        ),
        migrations.RemoveField(
            model_name='materiaprima',
            name='inventario_inicial',
        ),
        migrations.RemoveField(
            model_name='materiaprima',
            name='linea_produccion',
        ),
        migrations.RemoveField(
            model_name='materiaprima',
            name='numero_buzon',
        ),
        migrations.RemoveField(
            model_name='patroncorte',
            name='rollizo',
        ),
        migrations.RemoveField(
            model_name='rollizo',
            name='linea',
        ),
        migrations.RemoveField(
            model_name='rollizo',
            name='rollizo_largo',
        ),
        migrations.AddField(
            model_name='detallepedido',
            name='cantidad',
            field=models.PositiveIntegerField(default='0'),
        ),


        migrations.AddField(
            model_name='rollizo',
            name='largo',
            field=models.FloatField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rollizo',
            name='linea_produccion',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rollizo',
            name='nombre',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.materiaprima'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rollizo',
            name='numero_buzon',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rollizo',
            name='tipo_madera',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rollizo',
            name='volumen_inicial',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rollizo',
            name='volumen_procesado',
            field=models.FloatField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='materiaprima',
            name='cantidad',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='materiaprima',
            name='clase_diametrica',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='materiaprima',
            name='largo',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='fecha_emision',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.patroncorte'),
        ),
        migrations.AlterModelTable(
            name='rollizo',
            table=None,
        ),
    ]
