# Generated by Django 4.2.4 on 2023-09-13 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0079_rename_inventario_inicial_producto_inventario_bodega_inicial_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallepedido',
            name='cantidad',
            field=models.PositiveIntegerField(),
        ),

        migrations.AlterField(
            model_name='rollizo',
            name='nombre_rollizo',
            field=models.CharField(max_length=20),
        ),
    ]
