# Generated by Django 4.2.4 on 2023-09-20 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0079_remove_pedido_producto_pedido_producto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedido',
            old_name='fecha_emision',
            new_name='fecha_produccion',
        ),
        migrations.RenameField(
            model_name='pedido',
            old_name='codigo',
            new_name='orden_pedido',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='demanda',
            new_name='grado_urgencia',
        ),
        migrations.RenameField(
            model_name='rollizo',
            old_name='rollizo_largo',
            new_name='largo',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='cantidad',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='linea_produccion',
        ),
        migrations.AddField(
            model_name='cliente',
            name='mercado',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='puerto_destino',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='detallepedido',
            name='cantidad',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pedido',
            name='version',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='cantidad_piezas',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='cantidad_trozos',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='linea',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.linea', verbose_name='Linea'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='nombre_rollizo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.rollizo', verbose_name='Rollizo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='paquetes_saldo',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='paquetes_solicitados',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='patron_corte',
            field=models.ManyToManyField(to='core.patroncorte'),
        ),
        migrations.AddField(
            model_name='producto',
            name='piezas_xpaquete',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='piezas_xtrozo',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5),
            preserve_default=False,
        ),
    ]
