# Generated by Django 4.2.4 on 2023-09-13 00:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0080_alter_detallepedido_cantidad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='linea',
            name='capacidad_disponible',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='linea',
            name='capacidad_maxima',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='linea',
            name='nombre',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.materiaprima'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='linea',
            name='rollizo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.rollizo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='linea',
            name='velocidad_linea',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='materiaprima',
            name='procedencia',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='materiaprima',
            name='volumen_llegada',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rollizo',
            name='cantidad',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rollizo',
            name='conicidad',
            field=models.FloatField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rollizo',
            name='costo_almacenamiento',
            field=models.FloatField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rollizo',
            name='costo_procesamiento',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rollizo',
            name='inventario_buzon',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rollizo',
            name='inventario_final',
            field=models.FloatField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
