# Generated by Django 4.2.4 on 2023-09-26 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0080_remove_rollizo_rollizo_largo_rollizo_largo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='orden_pedido',
            field=models.CharField(max_length=20),
        ),
    ]
