# Generated by Django 4.2.4 on 2023-09-26 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0081_alter_pedido_orden_pedido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='orden_pedido',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
