# Generated by Django 4.2.4 on 2023-09-13 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0081_linea_capacidad_disponible_linea_capacidad_maxima_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='materiaprima',
            name='nombre',
            field=models.CharField(default='nombre', max_length=20),
            preserve_default=False,
        ),
    ]
