# Generated by Django 4.2.4 on 2023-09-26 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0083_rename_orden_pedido_pedido_orden_interna_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallepedido',
            name='mercado',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='detallepedido',
            name='puerto_detino',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
