# Generated by Django 4.2.4 on 2023-09-26 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0084_detallepedido_mercado_detallepedido_puerto_detino'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detallepedido',
            old_name='puerto_detino',
            new_name='puerto_destino',
        ),
    ]
