# Generated by Django 4.2.5 on 2023-09-27 14:59

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0085_rename_puerto_detino_detallepedido_puerto_destino'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empaque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pqte', models.DecimalField(decimal_places=3, max_digits=10, null=True)),
                ('tipo_empaque', models.CharField(max_length=40, null=True)),
                ('alto_paquete', models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('int_paquete', models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(0)])),
            ],
            options={
                'db_table': 'Paquete',
            },
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FSC', models.CharField(max_length=40, null=True)),
                ('esp_fact', models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('anc_fact', models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('lar_fact', models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(0)])),
            ],
            options={
                'db_table': 'Factura',
            },
        ),
        migrations.AddField(
            model_name='detallepedido',
            name='banio',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='detallepedido',
            name='calidad',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='detallepedido',
            name='marca',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='detallepedido',
            name='mbf',
            field=models.DecimalField(decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='detallepedido',
            name='piezas_cpo',
            field=models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='detallepedido',
            name='piezas_x_cpo',
            field=models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='detallepedido',
            name='programa',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='detallepedido',
            name='term',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='detallepedido',
            name='estado_pedido_linea',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='detallepedido',
            name='empaque',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.empaque', verbose_name='Empaque'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='detallepedido',
            name='factura',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='core.factura', verbose_name='Factura'),
            preserve_default=False,
        ),
    ]
