# Generated by Django 4.2.5 on 2023-09-27 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0087_rename_piezas_cpo_detallepedido_cpo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('', 'Seleccione una opción'), ('pendiente', 'Pendiente'), ('en proceso', 'En Proceso'), ('completado', 'Completado')], default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='orden_interna',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='prioridad',
            field=models.CharField(choices=[('', 'Seleccione una opción'), ('bajo', 'Bajo'), ('mediano', 'Mediano'), ('alto', 'Alto')], default='', max_length=20, null=True),
        ),
    ]
