# Generated by Django 4.2.4 on 2023-09-27 19:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0088_alter_pedido_estado_alter_pedido_orden_interna_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empaque',
            name='anc_paquete',
            field=models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
