# Generated by Django 4.2.5 on 2023-09-28 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0090_alter_detallepedido_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallepedido',
            name='est',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
