# Generated by Django 4.2.4 on 2023-09-28 21:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0091_detallepedido_est'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallepedido',
            name='diametro',
            field=models.FloatField(max_length=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='detallepedido',
            name='largo_trozo',
            field=models.FloatField(max_length=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='detallepedido',
            name='nota',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='detallepedido',
            name='separador',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('', 'Seleccione una opción'), ('pendiente', 'Pendiente'), ('en proceso', 'En Proceso'), ('completado', 'Completado')], default='pendiente', max_length=20, null=True),
        ),
    ]
