# Generated by Django 4.2.4 on 2023-10-02 22:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0093_alter_detallepedido_alto_producto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallepedido',
            name='largo_producto',
            field=models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
