# Generated by Django 4.2.4 on 2023-10-02 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0094_alter_detallepedido_alto_producto_and_more'),
        ('core', '0094_alter_detallepedido_largo_producto'),
    ]

    operations = [
    ]
