# Generated by Django 4.2.4 on 2023-10-04 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0095_merge_20231002_1946'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='eliminado',
            field=models.BooleanField(default=False),
        ),
    ]
