# Generated by Django 4.2.4 on 2023-10-03 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0096_pedido_eliminado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='eliminado',
        ),
    ]
