# Generated by Django 4.2.4 on 2023-10-13 21:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0096_pedido_eliminado'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallepedido',
            name='producto_key',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='stockproducto',
            name='detalle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.detallepedido', verbose_name='DetallePedido'),
        ),
    ]
