# Generated by Django 4.2.4 on 2023-10-03 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0097_remove_pedido_eliminado'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='eliminado',
            field=models.BooleanField(default=False),
        ),
    ]
