# Generated by Django 4.2.4 on 2023-10-14 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0098_stockproducto_producto_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockproducto',
            name='detalle',
        ),
    ]
