# Generated by Django 4.2.4 on 2023-10-16 23:36

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0099_remove_stockproducto_detalle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='costosobretiempo',
            name='valor',
        ),
        migrations.RemoveField(
            model_name='patroncorte',
            name='lead_time',
        ),
        migrations.RemoveField(
            model_name='patroncorte',
            name='setup_time',
        ),
        migrations.RemoveField(
            model_name='patroncorte',
            name='velocidad_linea',
        ),
        migrations.RemoveField(
            model_name='stockproducto',
            name='producto_key',
        ),
        migrations.AddField(
            model_name='costorollizo',
            name='rollizo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.rollizo', verbose_name='rollizo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='costosobretiempo',
            name='cantidad_horas',
            field=models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='costosobretiempo',
            name='costos_horas_extras',
            field=models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='costosobretiempo',
            name='linea',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.linea', verbose_name='Linea'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='detallepedido',
            name='fecha_salida',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='linea',
            name='patron',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.patroncorte', verbose_name='Patrón de Corte'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='linea',
            name='velocidad',
            field=models.DecimalField(decimal_places=3, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='lineahhdisponible',
            name='periodo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.periodo', verbose_name='Periodo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stockproducto',
            name='costo_almacenamiento',
            field=models.FloatField(max_length=10, null=True),
        ),

        migrations.AddField(
            model_name='stockproducto',
            name='valor_inventario',
            field=models.FloatField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='tiempocambio',
            name='Hrs_cambio',
            field=models.DecimalField(decimal_places=3, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='costorollizo',
            name='nombre_costo',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='costorollizo',
            name='valor_m3',
            field=models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='lineahhdisponible',
            name='cantidad_hh',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='lineahhdisponible',
            name='numero_bloque',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='patroncorte',
            name='descripcion',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='patroncorte',
            name='rendimiento',
            field=models.FloatField(max_length=5, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='patroncorte',
            name='rollizo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.rollizo', verbose_name='rollizo'),
        ),
        migrations.AlterField(
            model_name='productoterminado',
            name='fecha_produccion',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='stockproducto',
            name='cantidad_m3',
            field=models.FloatField(null=True),
        ),
    ]
