# Generated by Django 4.2.4 on 2023-10-16 23:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0100_remove_costosobretiempo_valor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patroncorte',
            name='rollizo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.rollizo', verbose_name='Rollizo'),
        ),
    ]
