# Generated by Django 4.2.4 on 2023-10-17 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0101_alter_patroncorte_rollizo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rollizo',
            name='linea',
        ),
    ]
