# Generated by Django 4.2.4 on 2023-10-17 13:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0103_remove_empresa_cliente_remove_empresa_productos_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alto_producto', models.DecimalField(decimal_places=3, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('ancho_producto', models.DecimalField(decimal_places=3, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('largo_producto', models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('eliminado', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='productosempresa',
            name='empresa',
        ),
        migrations.RemoveField(
            model_name='productosempresa',
            name='producto',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='alto',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='ancho',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='largo',
        ),
        migrations.DeleteModel(
            name='ClienteEmpresa',
        ),
        migrations.DeleteModel(
            name='ProductosEmpresa',
        ),
        migrations.AddField(
            model_name='producto',
            name='medida',
            field=models.ManyToManyField(to='core.medida'),
        ),
    ]
