# Generated by Django 4.2.4 on 2023-10-17 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0105_remove_detallepedido_producto_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockproducto',
            name='producto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.producto', verbose_name='Producto'),
            preserve_default=False,
        ),
    ]
