# Generated by Django 4.2.4 on 2023-10-18 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0109_alter_detallepedido_cantidad_trozos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallepedido',
            name='detalle_producto',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='detallepedido',
            name='fecha_entrega',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='detallepedido',
            name='folio',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='detallepedido',
            name='grado_urgencia',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
