# Generated by Django 4.2.4 on 2023-10-18 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0112_alter_pedido_prioridad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockproducto',
            name='producto',
        ),
        migrations.CreateModel(
            name='ProductoMedida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.medida', verbose_name='Medida')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.producto', verbose_name='Producto')),
            ],
            options={
                'db_table': 'producto_medida',
            },
        ),
        migrations.AddField(
            model_name='producto',
            name='medida',
            field=models.ManyToManyField(through='core.ProductoMedida', to='core.medida'),
        ),
        migrations.AddField(
            model_name='stockproducto',
            name='producto_medida',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.productomedida'),
            preserve_default=False,
        ),
    ]
