# Generated by Django 4.2.4 on 2023-10-25 14:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0113_remove_stockproducto_producto_productomedida_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='fecha_produccion',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
