# Generated by Django 4.2.4 on 2023-10-26 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0115_alter_pedido_fecha_produccion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Demanda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Medida_Producto_id', models.PositiveIntegerField(null=True)),
                ('dias_produccion', models.DateField(null=True)),
                ('Pqtes_Solicitados', models.PositiveIntegerField(null=True)),
                ('Pqtes_dia', models.PositiveIntegerField(null=True)),
                ('M3', models.FloatField(null=True)),
            ],
            options={
                'db_table': 'Demanda',
            },
        ),
    ]
