# Generated by Django 4.2.4 on 2023-10-30 21:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0117_remove_lineahhdisponible_cantidad_hh_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineahhdisponible',
            name='cantidad_hh',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
