# Generated by Django 4.2.5 on 2023-11-02 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0119_rendimiento_producto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patroncorte',
            name='codigo',
            field=models.CharField(default='', max_length=20),
        ),
    ]
