# Generated by Django 4.2.4 on 2023-11-02 21:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0119_rendimiento_producto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Demanda_Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('demanda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.demanda', verbose_name='Demanda')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.pedido', verbose_name='Pedido')),
            ],
            options={
                'db_table': 'Demanda_Producto',
            },
        ),
        migrations.AddField(
            model_name='demanda',
            name='pedido',
            field=models.ManyToManyField(through='core.Demanda_Producto', to='core.pedido'),
        ),
    ]
