# Generated by Django 4.2.4 on 2023-11-05 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0121_alter_bodega_fecha_crea_alter_bodega_usuario_crea_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rendimiento_producto',
            name='rendimiento',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stockrollizo',
            name='dias_produccion',
            field=models.DateField(null=True),
        ),
    ]
