# Generated by Django 4.2.4 on 2023-11-05 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0122_alter_rendimiento_producto_rendimiento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockrollizo',
            name='Costo_elab',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='stockrollizo',
            name='stock_entrante',
            field=models.FloatField(null=True),
        ),
    ]
