# Generated by Django 4.2.4 on 2023-11-05 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0123_alter_stockrollizo_costo_elab_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockproducto',
            name='costo_almacenamiento',
            field=models.FloatField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='stockproducto',
            name='valor_inventario',
            field=models.FloatField(max_length=10, null=True),
        ),
    ]
