# Generated by Django 4.2.4 on 2023-11-05 22:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0124_alter_stockproducto_costo_almacenamiento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallepedido',
            name='cpo',
            field=models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
