# Generated by Django 4.2.4 on 2023-11-05 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0125_alter_detallepedido_cpo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rendimiento_producto',
            name='rendimiento',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
