# Generated by Django 4.2.7 on 2023-11-08 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0126_alter_rendimiento_producto_rendimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patroncorte',
            name='codigo',
            field=models.CharField(default='', max_length=20),
        ),
    ]
