# Generated by Django 4.2.4 on 2023-10-04 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asignaciones', '0002_role_userprofile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('ADMINISTRADOR', 'Administrador'), ('PLANIFICADOR', 'Planificador'), ('BETECH', 'Betech')], default='', max_length=20, null=True),
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
