# Generated by Django 4.2.4 on 2023-10-04 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asignaciones', '0004_rename_role_userprofile_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='roles',
            field=models.CharField(choices=[('', 'Seleccione una opcion'), ('ADMINISTRADOR', 'Administrador'), ('PLANIFICADOR', 'Planificador'), ('BETECH', 'Betech')], default='', max_length=20, null=True),
        ),
    ]
