# Generated by Django 4.1.7 on 2023-03-21 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('asignaciones', '0004_alter_userprofile_empresa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='empresa',
            field=models.ForeignKey(db_column='rut_empresa', on_delete=django.db.models.deletion.CASCADE, to='core.empresa'),
        ),
    ]
